spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 881234

    data:
      redis:
        host: localhost
        port: 6379

# Automatically convert camel-case-naming and underscore-naming
# f.eks "createTime" in Java-class, but "create_time" in database
mybatis:
  configuration:
    map-underscore-to-camel-case: true